"use client";

import { useState } from "react";

type Format = "text" | "json" | "csv";
type ApiEnvelope<T> = { ok: boolean; data?: T; error?: { message?: string }; requestId?: string };

export function ImportListingForm({ onImported }: { onImported: (productId: string) => void }) {
  const [format, setFormat] = useState<Format>("text"); const [content, setContent] = useState(""); const [stage, setStage] = useState<"idle" | "importing" | "extracting">("idle"); const [error, setError] = useState<string | null>(null); const [requestId, setRequestId] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!content.trim()) { setError("Add a product listing before analysing it."); return; } setError(null); setRequestId(null); setStage("importing"); try { const imported = await fetch("/api/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ format, content }) }); const importBody = (await imported.json()) as ApiEnvelope<{ productIds: string[] }>; if (!imported.ok || !importBody.data?.productIds[0]) throw new Error(importBody.error?.message ?? "We could not import that listing."); const productId = importBody.data.productIds[0]; setStage("extracting"); const extracted = await fetch(`/api/products/${productId}/extract`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({}) }); const extractionBody = (await extracted.json()) as ApiEnvelope<unknown>; if (!extracted.ok) { setRequestId(extractionBody.requestId ?? null); throw new Error(extractionBody.error?.message ?? "We could not analyse that listing."); } onImported(productId); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong. Please try again."); } finally { setStage("idle"); } };
  return <form onSubmit={(event) => void submit(event)} className="surface-card mx-auto max-w-3xl p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Start with product truth</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Analyse a product listing</h1><p className="mt-3 max-w-2xl text-slate-600">Import the source listing. AgentReady Coach will identify the facts an AI shopper still cannot verify.</p><div className="mt-6 flex flex-wrap gap-2" role="tablist" aria-label="Listing format">{(["text", "json", "csv"] as Format[]).map((item) => <button key={item} type="button" role="tab" aria-selected={format === item} onClick={() => setFormat(item)} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize ${format === item ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-700"}`}>{item}</button>)}</div><label className="mt-5 block text-sm font-semibold">Product listing<textarea aria-label="Product listing" value={content} onChange={(event) => setContent(event.target.value)} className="mt-2 min-h-56 w-full rounded-xl border border-slate-300 bg-white p-4 text-slate-900" placeholder={format === "text" ? "CloudRun Pro\nA lightweight and comfortable running shoe..." : format === "json" ? '{ "name": "CloudRun Pro" }' : "name,description,price"} /></label>{error && <div role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}{requestId ? ` Request ID: ${requestId}` : ""}</div>}<button disabled={stage !== "idle"} className="mt-5 rounded-lg bg-gradient-to-r from-blue-600 to-indigo-600 px-5 py-3 font-semibold text-white shadow-lg shadow-blue-600/20 disabled:opacity-60">{stage === "importing" ? "Importing listing…" : stage === "extracting" ? "Building Product Passport…" : "Analyse listing"}</button></form>;
}
