"use client";

import { useEffect, useMemo, useState } from "react";
import type { ListingEvaluation } from "@/domain/evaluation";
import type { ProductPassport } from "@/domain/passport";
import { BeforeAfterPanel } from "./before-after-panel";
import { GapList } from "./gap-list";
import { makeMockDashboard } from "./mock-dashboard-data";
import { MarketInsights } from "./market-insights";
import { ProductPassportPanel } from "./product-passport-panel";
import { ReadinessBreakdown } from "./readiness-breakdown";
import { SellerChat, type SellerAnswer } from "./seller-chat";

type DashboardState = ReturnType<typeof makeMockDashboard>;

export function ProductDashboard({ productId }: { productId: string }) {
  const [dashboard, setDashboard] = useState<DashboardState>(() => makeMockDashboard(productId)); const [coachOpen, setCoachOpen] = useState(false); const [changed, setChanged] = useState<string[]>([]);
  useEffect(() => { let cancelled = false; const load = async () => { try { const response = await fetch(`/api/products/${productId}`); if (response.ok) { const body = await response.json() as { data?: Partial<DashboardState> }; if (!cancelled && body.data?.passport && body.data.evaluation && body.data.intelligence) setDashboard((current) => ({ ...current, ...body.data } as DashboardState)); } const evaluated = await fetch(`/api/products/${productId}/evaluate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({}) }); if (evaluated.ok) { const body = await evaluated.json() as { data?: { evaluation?: ListingEvaluation; intelligence?: DashboardState["intelligence"] } }; if (!cancelled && body.data?.evaluation) setDashboard((current) => ({ ...current, evaluation: body.data?.evaluation ?? current.evaluation, intelligence: body.data?.intelligence ?? current.intelligence })); } } catch { /* mock-first UI remains available until API integration */ } }; void load(); return () => { cancelled = true; }; }, [productId]);
  const activeGap = coachOpen ? dashboard.evaluation.gaps[0] ?? null : null;
  const activeDefinition = useMemo(() => dashboard.intelligence.features.find((feature) => feature.key === activeGap?.featureKey), [dashboard.intelligence.features, activeGap?.featureKey]);
  const openCoach = async () => { setCoachOpen(true); if (dashboard.sessionId) return; try { const response = await fetch(`/api/products/${productId}/interviews`, { method: "POST" }); const body = await response.json() as { data?: { sessionId?: string } }; if (response.ok && body.data?.sessionId) setDashboard((current) => ({ ...current, sessionId: body.data?.sessionId ?? "mock-session-1" })); else setDashboard((current) => ({ ...current, sessionId: "mock-session-1" })); } catch { setDashboard((current) => ({ ...current, sessionId: "mock-session-1" })); } };
  const applyAnswer = async (answer: SellerAnswer) => { if (dashboard.sessionId && !dashboard.sessionId.startsWith("mock-")) { const response = await fetch(`/api/interviews/${dashboard.sessionId}/answers`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(answer) }); const body = await response.json() as { data?: { passport?: ProductPassport; evaluation?: ListingEvaluation } }; if (!response.ok || !body.data?.passport || !body.data.evaluation) throw new Error("Answer update failed"); setDashboard((current) => ({ ...current, passport: body.data?.passport ?? current.passport, evaluation: body.data?.evaluation ?? current.evaluation })); setChanged([answer.featureKey]); return; } const index = dashboard.evaluation.gaps.findIndex((gap) => gap.featureKey === answer.featureKey); const feature = dashboard.passport.features.find((item) => item.key === answer.featureKey); const nextFeatures = dashboard.passport.features.map((item) => item.key !== answer.featureKey ? item : { ...item, value: answer.value, unit: answer.unit, status: answer.unknown ? "missing" as const : answer.evidenceText ? "verified" as const : "seller_declared" as const, confidence: answer.unknown ? 0 : answer.evidenceText ? 1 : 0.6 }); const nextGaps = answer.unknown || index < 0 ? dashboard.evaluation.gaps : dashboard.evaluation.gaps.filter((gap) => gap.featureKey !== answer.featureKey); const improvement = answer.unknown ? 0 : 14; const nextEvaluation: ListingEvaluation = { ...dashboard.evaluation, readiness: { ...dashboard.evaluation.readiness, completeness: Math.min(100, dashboard.evaluation.readiness.completeness + improvement), evidenceQuality: Math.min(100, dashboard.evaluation.readiness.evidenceQuality + improvement), intentCoverage: Math.min(100, dashboard.evaluation.readiness.intentCoverage + improvement), total: Math.min(100, dashboard.evaluation.readiness.total + improvement) }, competitiveness: { ...dashboard.evaluation.competitiveness, peerFeatureCoverage: Math.min(100, dashboard.evaluation.competitiveness.peerFeatureCoverage + improvement), highDemandQueryCoverage: Math.min(100, dashboard.evaluation.competitiveness.highDemandQueryCoverage + improvement), total: Math.min(100, dashboard.evaluation.competitiveness.total + improvement) }, gaps: nextGaps, generatedAt: new Date().toISOString() }; setDashboard((current) => ({ ...current, passport: { ...current.passport, features: nextFeatures, updatedAt: new Date().toISOString() }, evaluation: nextEvaluation, sessionId: current.sessionId ?? "mock-session-1" })); if (feature) setChanged([feature.key]); };
  return <main id="main-content" className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">AgentReady Coach / Product workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Make product truth recommendation-ready</h1></div><button onClick={() => void openCoach()} className="rounded-lg bg-gradient-to-r from-blue-600 to-indigo-600 px-4 py-3 font-semibold text-white">Open seller coach</button></header><div className="grid gap-5 lg:grid-cols-5"><div className="order-1 lg:col-span-2">{coachOpen ? <SellerChat sessionId={dashboard.sessionId} gap={activeGap} definition={activeDefinition} onUpdate={applyAnswer} /> : <section className="surface-card bg-[var(--navy)] p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Guided optimisation</p><h2 className="mt-1 text-xl font-semibold">Let the coach find your next best answer</h2><p className="mt-3 text-sm text-slate-300">Prioritised questions connect missing product facts to real shopper demand.</p><button onClick={() => void openCoach()} className="mt-4 rounded-lg bg-white px-4 py-2 font-semibold text-slate-950">Open seller coach</button></section>}</div><div className="order-2 lg:col-span-2"><ProductPassportPanel passport={dashboard.passport} definitions={dashboard.intelligence.features} changedFeatureKeys={changed} /></div><aside className="order-3 space-y-5 lg:col-span-1"><ReadinessBreakdown readiness={dashboard.evaluation.readiness} competitiveness={dashboard.evaluation.competitiveness} /></aside><div className="order-4 space-y-5 lg:col-span-2"><GapList gaps={dashboard.evaluation.gaps} /></div><div className="order-5 space-y-5 lg:col-span-3"><MarketInsights intelligence={dashboard.intelligence} /></div></div><div className="mt-5"><BeforeAfterPanel productId={productId} /></div></main>;
}
